# Generated by Django 5.1.5 on 2025-01-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='treatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmapp.treatment'),
        ),
    ]
