# Generated by Django 5.1.5 on 2025-01-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmapp', '0002_alter_doctor_fees_alter_doctor_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
