# Generated by Django 5.1.5 on 2025-01-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
        ('hmapp', '0002_alter_doctor_fees_alter_doctor_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmapp.doctor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
