# Generated by Django 5.1.5 on 2025-01-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_remove_booking_doctor'),
        ('hmapp', '0002_alter_doctor_fees_alter_doctor_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmapp.doctor'),
            preserve_default=False,
        ),
    ]
